<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\ValidationRule;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class UpdateFunnelRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return $this->user() !== null;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        $funnelId = (int) $this->route('funnel')->id;

        return [
            'name' => ['required', 'string', 'max:120'],
            'is_active' => ['required', 'boolean'],
            'completion_page' => ['nullable', 'array'],
            'completion_page.enabled' => ['nullable', 'boolean'],
            'completion_page.title' => ['nullable', 'string', 'max:180'],
            'completion_page.description' => ['nullable', 'string', 'max:500'],
            'completion_page.image_url' => ['nullable', 'string', 'max:1500000'],
            'completion_page.primary_button_text' => ['nullable', 'string', 'max:80'],
            'completion_page.primary_button_url' => ['nullable', 'string', 'max:500'],
            'completion_page.primary_button_new_tab' => ['nullable', 'boolean'],
            'completion_page.secondary_button_text' => ['nullable', 'string', 'max:80'],
            'completion_page.secondary_button_url' => ['nullable', 'string', 'max:500'],
            'completion_page.secondary_button_new_tab' => ['nullable', 'boolean'],
            'completion_page.auto_redirect_url' => ['nullable', 'string', 'max:500'],
            'completion_page.auto_redirect_delay_seconds' => ['nullable', 'integer', 'min:0', 'max:600'],
            'stages' => ['required', 'array', 'min:2'],
            'stages.*.id' => [
                'nullable',
                'integer',
                Rule::exists('funnel_stages', 'id')->where('funnel_id', $funnelId),
            ],
            'stages.*.name' => ['required', 'string', 'max:120'],
            'stages.*.conversion_rate' => ['nullable', 'numeric', 'between:0,100'],
            'stages.*.expected_volume' => ['nullable', 'integer', 'min:0'],
            'stages.*.meta' => ['nullable', 'array'],
            'stages.*.meta.header' => ['nullable', 'array'],
            'stages.*.meta.header.show_logo' => ['nullable', 'boolean'],
            'stages.*.meta.header.show_progress' => ['nullable', 'boolean'],
            'stages.*.meta.header.allow_back' => ['nullable', 'boolean'],
            'stages.*.meta.builder' => ['nullable', 'array'],
            'stages.*.meta.builder.title' => ['nullable', 'string', 'max:180'],
            'stages.*.meta.builder.subtitle' => ['nullable', 'string', 'max:300'],
            'stages.*.meta.builder.button_text' => ['nullable', 'string', 'max:80'],
            'stages.*.meta.builder.blocks' => ['nullable', 'array'],
            'stages.*.meta.builder.blocks.*.id' => ['required_with:stages.*.meta.builder.blocks', 'string', 'max:120'],
            'stages.*.meta.builder.blocks.*.type' => ['required_with:stages.*.meta.builder.blocks', 'string', 'max:40'],
            'stages.*.meta.builder.blocks.*.label' => ['nullable', 'string', 'max:120'],
            'stages.*.meta.builder.blocks.*.placeholder' => ['nullable', 'string', 'max:1500000'],
            'stages.*.meta.builder.blocks.*.variable_name' => ['nullable', 'string', 'max:64', 'regex:/^[A-Za-z0-9_-]+$/'],
            'stages.*.meta.builder.blocks.*.required' => ['required_with:stages.*.meta.builder.blocks', 'boolean'],
            'stages.*.meta.builder.blocks.*.options' => ['nullable', 'array'],
            'stages.*.meta.builder.blocks.*.options.*' => ['nullable', 'string', 'max:120'],
            'stages.*.meta.builder.blocks.*.option_items' => ['nullable', 'array'],
            'stages.*.meta.builder.blocks.*.option_items.*.id' => ['required_with:stages.*.meta.builder.blocks.*.option_items', 'string', 'max:120'],
            'stages.*.meta.builder.blocks.*.option_items.*.label' => ['nullable', 'string', 'max:120'],
            'stages.*.meta.builder.blocks.*.option_items.*.points' => ['nullable', 'numeric'],
            'stages.*.meta.builder.blocks.*.option_items.*.value' => ['nullable', 'string', 'max:1500000'],
            'stages.*.meta.builder.blocks.*.option_items.*.destination' => ['nullable', 'string', 'max:120'],
            'stages.*.meta.builder.blocks.*.option_items.*.image_url' => ['nullable', 'string', 'max:1500000'],
            'stages.*.meta.builder.blocks.*.option_items.*.subtitle' => ['nullable', 'string', 'max:180'],
            'stages.*.meta.builder.blocks.*.option_items.*.description' => ['nullable', 'string', 'max:1500000'],
            'stages.*.meta.builder.blocks.*.option_items.*.rating' => ['nullable', 'numeric', 'between:1,5'],
            'stages.*.meta.builder.blocks.*.options_intro_type' => ['nullable', Rule::in(['text', 'none'])],
            'stages.*.meta.builder.blocks.*.options_intro_title' => ['nullable', 'string', 'max:180'],
            'stages.*.meta.builder.blocks.*.options_intro_description' => ['nullable', 'string', 'max:300'],
            'stages.*.meta.builder.blocks.*.options_required_selection' => ['nullable', 'boolean'],
            'stages.*.meta.builder.blocks.*.options_allow_multiple' => ['nullable', 'boolean'],
            'stages.*.meta.builder.blocks.*.options_disable_auto_follow' => ['nullable', 'boolean'],
            'stages.*.meta.builder.blocks.*.options_style' => ['nullable', Rule::in(['simple', 'highlight', 'relief', 'contrast', 'cards'])],
            'stages.*.meta.builder.blocks.*.options_transparent_image' => ['nullable', 'boolean'],
            'stages.*.meta.builder.blocks.*.options_layout' => ['nullable', Rule::in(['grid_2', 'grid_1'])],
            'stages.*.meta.builder.blocks.*.options_orientation' => ['nullable', Rule::in(['vertical', 'horizontal'])],
            'stages.*.meta.builder.blocks.*.options_image_ratio' => ['nullable', Rule::in(['1:1', '4:3', '16:9'])],
            'stages.*.meta.builder.blocks.*.options_disposition' => ['nullable', Rule::in(['image_text', 'text_image', 'text'])],
            'stages.*.meta.builder.blocks.*.options_detail' => ['nullable', Rule::in(['checkout', 'arrow', 'points', 'value', 'none'])],
            'stages.*.meta.builder.blocks.*.options_detail_position' => ['nullable', Rule::in(['start', 'end'])],
            'stages.*.meta.builder.blocks.*.options_border_size' => ['nullable', Rule::in(['small', 'medium', 'large'])],
            'stages.*.meta.builder.blocks.*.options_shadow' => ['nullable', Rule::in(['none', 'soft', 'strong'])],
            'stages.*.meta.builder.blocks.*.options_spacing' => ['nullable', Rule::in(['simple', 'comfortable', 'compact'])],
            'stages.*.meta.builder.blocks.*.testimonials_layout' => ['nullable', Rule::in(['list', 'slide', 'grid'])],
            'stages.*.meta.builder.blocks.*.faq_first_active' => ['nullable', 'boolean'],
            'stages.*.meta.builder.blocks.*.faq_detail' => ['nullable', Rule::in(['arrow', 'chevron', 'plus_minus', 'none'])],
            'stages.*.meta.builder.blocks.*.price_title' => ['nullable', 'string', 'max:180'],
            'stages.*.meta.builder.blocks.*.price_prefix' => ['nullable', 'string', 'max:120'],
            'stages.*.meta.builder.blocks.*.price_value' => ['nullable', 'string', 'max:120'],
            'stages.*.meta.builder.blocks.*.price_suffix' => ['nullable', 'string', 'max:120'],
            'stages.*.meta.builder.blocks.*.price_badge_text' => ['nullable', 'string', 'max:120'],
            'stages.*.meta.builder.blocks.*.price_mode' => ['nullable', Rule::in(['illustrative', 'redirect'])],
            'stages.*.meta.builder.blocks.*.price_layout' => ['nullable', Rule::in(['horizontal', 'vertical'])],
            'stages.*.meta.builder.blocks.*.price_style' => ['nullable', Rule::in(['theme', 'light', 'dark'])],
            'stages.*.meta.builder.blocks.*.price_link' => ['nullable', 'string', 'max:500'],
            'stages.*.meta.builder.blocks.*.carousel_layout' => ['nullable', Rule::in(['image_text', 'image_only', 'text_only'])],
            'stages.*.meta.builder.blocks.*.carousel_pagination' => ['nullable', 'boolean'],
            'stages.*.meta.builder.blocks.*.carousel_autoplay' => ['nullable', 'boolean'],
            'stages.*.meta.builder.blocks.*.carousel_autoplay_seconds' => ['nullable', 'integer', 'min:1', 'max:60'],
            'stages.*.meta.builder.blocks.*.carousel_border_type' => ['nullable', Rule::in(['none', 'subtle', 'strong'])],
            'stages.*.meta.builder.blocks.*.image_ratio' => ['nullable', Rule::in(['auto', '16:9', '4:3', '1:1'])],
            'stages.*.meta.builder.blocks.*.image_fit' => ['nullable', Rule::in(['cover', 'contain'])],
            'stages.*.meta.builder.blocks.*.image_radius' => ['nullable', Rule::in(['none', 'small', 'medium', 'large', 'full'])],
            'stages.*.meta.builder.blocks.*.image_frame' => ['nullable', Rule::in(['none', 'subtle', 'strong'])],
            'stages.*.meta.builder.blocks.*.video_ratio' => ['nullable', Rule::in(['16:9', '4:3', '1:1'])],
            'stages.*.meta.builder.blocks.*.audio_sender' => ['nullable', 'string', 'max:120'],
            'stages.*.meta.builder.blocks.*.audio_src' => ['nullable', 'string', 'max:1500000'],
            'stages.*.meta.builder.blocks.*.audio_avatar_url' => ['nullable', 'string', 'max:1500000'],
            'stages.*.meta.builder.blocks.*.audio_model' => ['nullable', Rule::in(['whatsapp'])],
            'stages.*.meta.builder.blocks.*.audio_theme' => ['nullable', Rule::in(['light', 'dark'])],
            'stages.*.meta.builder.blocks.*.attention_style' => ['nullable', Rule::in(['red', 'amber', 'blue'])],
            'stages.*.meta.builder.blocks.*.attention_emphasis' => ['nullable', 'boolean'],
            'stages.*.meta.builder.blocks.*.attention_padding' => ['nullable', Rule::in(['compact', 'default', 'comfortable'])],
            'stages.*.meta.builder.blocks.*.notification_title' => ['nullable', 'string', 'max:180'],
            'stages.*.meta.builder.blocks.*.notification_description' => ['nullable', 'string', 'max:500'],
            'stages.*.meta.builder.blocks.*.notification_avatar_url' => ['nullable', 'string', 'max:1500000'],
            'stages.*.meta.builder.blocks.*.notification_position' => ['nullable', Rule::in(['default', 'top_left', 'top_center', 'top_right', 'bottom_left', 'bottom_center', 'bottom_right'])],
            'stages.*.meta.builder.blocks.*.notification_duration_seconds' => ['nullable', 'integer', 'min:1', 'max:600'],
            'stages.*.meta.builder.blocks.*.notification_interval_seconds' => ['nullable', 'integer', 'min:1', 'max:600'],
            'stages.*.meta.builder.blocks.*.notification_style' => ['nullable', Rule::in(['white', 'dark', 'blue'])],
            'stages.*.meta.builder.blocks.*.notification_size' => ['nullable', Rule::in(['compact', 'default', 'large'])],
            'stages.*.meta.builder.blocks.*.notification_variant' => ['nullable', Rule::in(['social', 'offer', 'message'])],
            'stages.*.meta.builder.blocks.*.notification_variations' => ['nullable', 'array'],
            'stages.*.meta.builder.blocks.*.notification_variations.*.id' => ['required_with:stages.*.meta.builder.blocks.*.notification_variations', 'string', 'max:120'],
            'stages.*.meta.builder.blocks.*.notification_variations.*.value1' => ['nullable', 'string', 'max:180'],
            'stages.*.meta.builder.blocks.*.notification_variations.*.value2' => ['nullable', 'string', 'max:180'],
            'stages.*.meta.builder.blocks.*.notification_variations.*.value3' => ['nullable', 'string', 'max:180'],
            'stages.*.meta.builder.blocks.*.notification_variations.*.value4' => ['nullable', 'string', 'max:1500000'],
            'stages.*.meta.builder.blocks.*.timer_seconds' => ['nullable', 'integer', 'min:1', 'max:3600'],
            'stages.*.meta.builder.blocks.*.timer_text' => ['nullable', 'string', 'max:500'],
            'stages.*.meta.builder.blocks.*.timer_style' => ['nullable', Rule::in(['red', 'amber', 'blue'])],
            'stages.*.meta.builder.blocks.*.loading_start_seconds' => ['nullable', 'integer', 'min:0', 'max:100'],
            'stages.*.meta.builder.blocks.*.loading_duration_seconds' => ['nullable', 'integer', 'min:1', 'max:600'],
            'stages.*.meta.builder.blocks.*.loading_navigation_action' => ['nullable', Rule::in(['next_stage', 'open_link', 'none'])],
            'stages.*.meta.builder.blocks.*.loading_target_stage_order' => ['nullable', 'string', 'max:10'],
            'stages.*.meta.builder.blocks.*.loading_link' => ['nullable', 'string', 'max:500'],
            'stages.*.meta.builder.blocks.*.loading_show_title' => ['nullable', 'boolean'],
            'stages.*.meta.builder.blocks.*.loading_show_progress' => ['nullable', 'boolean'],
            'stages.*.meta.builder.blocks.*.level_title' => ['nullable', 'string', 'max:180'],
            'stages.*.meta.builder.blocks.*.level_subtitle' => ['nullable', 'string', 'max:300'],
            'stages.*.meta.builder.blocks.*.level_percentage' => ['nullable', 'numeric', 'between:0,100'],
            'stages.*.meta.builder.blocks.*.level_indicator_text' => ['nullable', 'string', 'max:120'],
            'stages.*.meta.builder.blocks.*.level_legends' => ['nullable', 'string', 'max:500'],
            'stages.*.meta.builder.blocks.*.level_show_meter' => ['nullable', 'boolean'],
            'stages.*.meta.builder.blocks.*.level_show_progress' => ['nullable', 'boolean'],
            'stages.*.meta.builder.blocks.*.level_type' => ['nullable', Rule::in(['line'])],
            'stages.*.meta.builder.blocks.*.level_color' => ['nullable', Rule::in(['theme', 'blue', 'green', 'red'])],
            'stages.*.meta.builder.blocks.*.phone_mask' => ['nullable', Rule::in(['br', 'us', 'eu'])],
            'stages.*.meta.builder.blocks.*.number_mask' => ['nullable', Rule::in(['decimal', 'real', 'dollar', 'euro'])],
            'stages.*.meta.builder.blocks.*.height_mode' => ['nullable', Rule::in(['ruler', 'input'])],
            'stages.*.meta.builder.blocks.*.weight_mode' => ['nullable', Rule::in(['ruler', 'input'])],
            'stages.*.meta.builder.blocks.*.button_action' => ['nullable', Rule::in(['next_stage', 'open_link'])],
            'stages.*.meta.builder.blocks.*.button_target_stage_order' => ['nullable', 'string', 'max:10'],
            'stages.*.meta.builder.blocks.*.button_link' => ['nullable', 'string', 'max:500'],
            'stages.*.meta.builder.blocks.*.button_open_new_tab' => ['nullable', 'boolean'],
            'stages.*.meta.builder.blocks.*.button_color_style' => ['nullable', Rule::in(['theme', 'dark', 'light'])],
            'stages.*.meta.builder.blocks.*.button_animated' => ['nullable', 'boolean'],
            'stages.*.meta.builder.blocks.*.button_elevated' => ['nullable', 'boolean'],
            'stages.*.meta.builder.blocks.*.button_sticky_footer' => ['nullable', 'boolean'],
            'stages.*.meta.builder.blocks.*.label_style' => ['nullable', Rule::in(['default', 'muted', 'hidden'])],
            'stages.*.meta.builder.blocks.*.text_align' => ['nullable', Rule::in(['text-left', 'text-center', 'text-right'])],
            'stages.*.meta.builder.blocks.*.width_percent' => ['nullable', 'numeric', 'between:25,100'],
            'stages.*.meta.builder.blocks.*.align_horizontal' => ['nullable', Rule::in(['start', 'center', 'end'])],
            'stages.*.meta.builder.blocks.*.align_vertical' => ['nullable', Rule::in(['start', 'center', 'end'])],
            'stages.*.meta.builder.blocks.*.show_after_seconds' => ['nullable', 'integer', 'min:0'],
            'stages.*.meta.builder.blocks.*.display_rule_mode' => ['nullable', Rule::in(['all', 'any'])],
            'stages.*.meta.builder.blocks.*.display_rules' => ['nullable', 'array'],
            'stages.*.meta.builder.blocks.*.display_rules.*.id' => ['nullable', 'string', 'max:120'],
            'stages.*.meta.builder.blocks.*.display_rules.*.source_block_id' => ['required', 'string', 'max:120'],
            'stages.*.meta.builder.blocks.*.display_rules.*.operator' => ['required', Rule::in(['filled', 'empty', 'equals', 'not_equals', 'contains_any', 'contains_all'])],
            'stages.*.meta.builder.blocks.*.display_rules.*.value' => ['nullable', 'string', 'max:180'],
            'stages.*.meta.builder.blocks.*.display_rule_groups' => ['nullable', 'array'],
            'stages.*.meta.builder.blocks.*.display_rule_groups.*.id' => ['nullable', 'string', 'max:120'],
            'stages.*.meta.builder.blocks.*.display_rule_groups.*.mode' => ['required', Rule::in(['all', 'any'])],
            'stages.*.meta.builder.blocks.*.display_rule_groups.*.rules' => ['required', 'array'],
            'stages.*.meta.builder.blocks.*.display_rule_groups.*.rules.*.id' => ['nullable', 'string', 'max:120'],
            'stages.*.meta.builder.blocks.*.display_rule_groups.*.rules.*.source_block_id' => ['required', 'string', 'max:120'],
            'stages.*.meta.builder.blocks.*.display_rule_groups.*.rules.*.operator' => ['required', Rule::in(['filled', 'empty', 'equals', 'not_equals', 'contains_any', 'contains_all'])],
            'stages.*.meta.builder.blocks.*.display_rule_groups.*.rules.*.value' => ['nullable', 'string', 'max:180'],
        ];
    }

    /**
     * @return array<string, string>
     */
    public function messages(): array
    {
        return [
            'name.required' => 'Informe o nome do funil.',
            'stages.required' => 'Defina as etapas do funil.',
            'stages.min' => 'Defina ao menos duas etapas para o funil.',
            'stages.*.name.required' => 'Informe o nome de cada etapa.',
            'stages.*.meta.builder.blocks.*.id.required_with' => 'Um dos componentes da etapa esta sem identificador valido.',
            'stages.*.meta.builder.blocks.*.type.required_with' => 'Um dos componentes da etapa esta sem tipo valido.',
            'stages.*.meta.builder.blocks.*.placeholder.max' => 'O conteudo de um dos blocos excede o limite permitido para salvamento.',
            'stages.*.meta.builder.blocks.*.option_items.*.value.max' => 'O valor de um dos itens excede o limite permitido para salvamento.',
            'stages.*.meta.builder.blocks.*.display_rules.*.source_block_id.required' => 'Selecione o componente de origem para cada regra de exibicao.',
            'stages.*.meta.builder.blocks.*.display_rule_groups.*.rules.*.source_block_id.required' => 'Selecione o componente de origem para cada regra de exibicao.',
        ];
    }
}
